image: "localhost:5001/logstash/logstash"

logstashConfig:
  logstash.yml: |
    http.host: 0.0.0.0
    xpack.monitoring.enabled: false

logstashPipeline:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
      tcp {
        port => 5050
        codec => json
      }
    }

    filter {
    }

    output {
      if [@metadata][beat] == "filebeat" {
        kafka {
          bootstrap_servers => "kafka.kafka.svc.cluster.local:9092"
          topic_id => "logs"
          codec => json
        }
      } else if [@metadata][beat] == "metricbeat" {
        kafka {
          bootstrap_servers => "kafka.kafka.svc.cluster.local:9092"
          topic_id => "metrics"
          codec => json
        }
      } else if [type] == "alert" {
        kafka {
          bootstrap_servers => "kafka.kafka.svc.cluster.local:9092"
          topic_id => "alerts"
          codec => json
        }
      } else {
        kafka {
          bootstrap_servers => "kafka.kafka.svc.cluster.local:9092"
          topic_id => "default"
          codec => json
        }
      }
    }

service:
  type: ClusterIP
  ports:
    - name: beats
      port: 5044
      protocol: TCP
      targetPort: 5044
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080

resources:
  requests:
    cpu: "200m"
    memory: "200Mi"
  limits:
    cpu: "1000m"
    memory: "1536Mi" 